using LegacyModernization.Analyzer.Models;
using LegacyModernization.LLM.Models;
using Microsoft.Extensions.Configuration;
using Mscc.GenerativeAI;

namespace LegacyModernization.LLM.Services;

public class GeminiService : ILlmService
{
    private readonly GoogleAI _googleAI;

    public GeminiService()
    {
        var config = new ConfigurationBuilder()
            .SetBasePath(AppContext.BaseDirectory)
            .AddJsonFile("appsettings.json", optional: false)
            .Build();

        var apiKey = config["Gemini:ApiKey"]
                     ?? throw new Exception("Gemini API key not found.");

        _googleAI = new GoogleAI(apiKey);
    }

    public async Task<RefactorSuggestion> GenerateSuggestionAsync(AnalysisIssue issue)
    {
        var model = _googleAI.GenerativeModel("gemini-3.6-flash");

        var prompt = $"""
You are a senior .NET modernization expert.

Rule:
{issue.RuleId}

Title:
{issue.Title}

Description:
{issue.Description}

Code:
{issue.CodeSnippet}

Explain:
1. Why this is a problem.
2. The modern replacement.
3. Show corrected C# code.
""";

        var response = await model.GenerateContent(prompt);

        return new RefactorSuggestion
        {
            RuleId = issue.RuleId,
            IssueTitle = issue.Title,
            Reason = issue.Description,
            OriginalCode = issue.CodeSnippet,
            RefactoredCode = response.Text,
            Explanation = "Generated by Gemini",
            IsSafe = true
        };
    }
}