using Mscc.GenerativeAI;
using System.IO;
using LegacyModernization.Core.Models;
using Microsoft.Extensions.Configuration;

namespace LegacyModernization.TestGenerator.Services;

public class GeminiTestGenerator : ITestGenerator
{
    private readonly string? _apiKey;

    public GeminiTestGenerator(IConfiguration? configuration = null)
    {
        var apiKey = Environment.GetEnvironmentVariable("GEMINI_API_KEY")
                     ?? configuration?["Gemini:ApiKey"];

        _apiKey = apiKey;
    }

    public async Task<GeneratedTest> GenerateTestAsync(AnalysisIssue issue)
    {
        if (string.IsNullOrWhiteSpace(_apiKey))
        {
            return new GeneratedTest
            {
                TestClassName = $"{issue.RuleId}GeneratedTests",
                TargetFile = issue.FilePath,
                Explanation = "No external model is configured; test generation is pending manual or local-model configuration."
            };
        }

        // Attempt to include the original source file as context so Gemini can generate a test against
        // the real class/method names instead of inventing them from the snippet alone.
        string fileContent = string.Empty;
        try
        {
            var candidates = new[]
            {
                issue.FilePath,
                Path.Combine(AppContext.BaseDirectory, issue.FilePath ?? ""),
                Path.Combine(Directory.GetCurrentDirectory(), issue.FilePath ?? ""),
                Path.GetFullPath(issue.FilePath ?? string.Empty)
            };

            string found = candidates.FirstOrDefault(p => !string.IsNullOrWhiteSpace(p) && File.Exists(p));
            if (!string.IsNullOrEmpty(found))
            {
                fileContent = File.ReadAllText(found);
            }
        }
        catch
        {
            // ignore read errors; we'll proceed without file context
            fileContent = string.Empty;
        }

        var prompt = $"""
You are a senior .NET testing engineer.

Generate an xUnit test for the following legacy C# issue.

Rule:
{issue.RuleId}

Title:
{issue.Title}

Description:
{issue.Description}

File:
{issue.FilePath}

Code:
{issue.CodeSnippet}

Context (if available):
{fileContent}

Use the source code above as the authoritative context. If a method or class is present in the source,
generate the test targeting the real class/method names. Do not invent new class names.

Requirements:

1. Use xUnit.
2. Test the CURRENT behavior of the legacy code.
3. Do not modify the production code.
4. Return ONLY compilable C# code.
5. Include all necessary using statements.
6. Create a meaningful test class and test method.
7. Do not use Markdown code fences.
8. The test must contain at least one [Fact] or [Theory].
""";

        var model = new GoogleAI(_apiKey).GenerativeModel(GetModelName());
        if (model is null)
        {
            return new GeneratedTest
            {
                TestClassName = $"{issue.RuleId}GeneratedTests",
                TargetFile = issue.FilePath,
                Explanation = "Gemini did not return a generative model."
            };
        }

        var generationTask = model.GenerateContent(prompt);
        var completedTask = await Task.WhenAny(
            generationTask,
            Task.Delay(GetTimeout()));

        if (completedTask != generationTask)
        {
            return new GeneratedTest
            {
                TestClassName = $"{issue.RuleId}GeneratedTests",
                TargetFile = issue.FilePath,
                Explanation = $"Gemini test generation timed out after {GetTimeout().TotalSeconds:0} seconds."
            };
        }

        var response = await generationTask;

        return new GeneratedTest
        {
            TestClassName = $"{issue.RuleId}GeneratedTests",
            TestCode = response.Text ?? "",
            TargetFile = issue.FilePath,
            Explanation = "Generated by Gemini"
        };
    }

    private static TimeSpan GetTimeout() =>
        TimeSpan.FromSeconds(
            int.TryParse(Environment.GetEnvironmentVariable("GEMINI_TIMEOUT_SECONDS"), out var seconds)
                ? Math.Clamp(seconds, 5, 300)
                : 20);

    private static string GetModelName() =>
        Environment.GetEnvironmentVariable("GEMINI_MODEL") ?? "gemini-3.8-flash";
}